# Generated by Django 5.2 on 2025-04-19 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rune_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(713)])),
                ('weapon_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.platform')),
            ],
        ),
    ]
