# Generated by Django 5.2 on 2025-04-19 18:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.area')),
            ],
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('is_win', models.BooleanField()),
                ('is_loss', models.BooleanField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.role')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(713)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.character')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.location')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.outcomes')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.role')),
            ],
        ),
    ]
