# Generated by Django 5.2 on 2025-04-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_area_role_location_outcomes_encounter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcomes',
            new_name='Outcome',
        ),
    ]
