# Generated by Django 5.2 on 2025-04-19 19:05

from django.db import migrations

def load_roles(apps, schema_editor):
    Role = apps.get_model("census","Role")
    db_alias = schema_editor.connection.alias
    for role in ['gold','red','blue']:
        Role.objects.using(db_alias).create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_rename_outcomes_outcome'),
    ]

    operations = [
        migrations.RunPython(load_roles)
    ]
