# Generated by Django 5.2 on 2025-04-19 19:31

from django.db import migrations
import json

def populate_regions(apps, schema_editor):
    Area = apps.get_model('census', 'Area')
    Location = apps.get_model('census', 'Location')
    db_alias = schema_editor.connection.alias
    with open('census/migrations/seed_data/regions.json', 'r') as file:
        data = json.load(file)
        for idx, region in enumerate(data, start=1):
            area, created = Area.objects.using(db_alias).get_or_create(
                                name=region['map'],
                                defaults={'sort_order': idx}
                            )
            location, created = Location.objects.using(db_alias).get_or_create(
                                    area=area,
                                    name=region['name'],
                                    defaults={'sort_order': idx}
                                )

class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_seed_roles'),
    ]

    operations = [
        migrations.RunPython(populate_regions)
    ]
