# Generated by Django 5.2 on 2025-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_seed_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='host_runes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
