# Generated by Django 5.2 on 2025-04-20 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_seed_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='host_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(713)]),
        ),
    ]
