# Generated by Django 5.2 on 2025-04-29 03:05

import django.db.models.deletion
from django.db import migrations, models

def populate_coop_types(apps, schema_editor):
    CoopType = apps.get_model('census', 'CoopType')
    db_alias = schema_editor.connection.alias
    types = [
        'Normal Progression',
        'Boss Door',
        'Dedicated Gank',
        'Solo TT',
        'Fight Club',
    ]
    for idx, coop_type in enumerate(types):
        CoopType.objects.using(db_alias).create(description=coop_type, sort_order = idx)



class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_encounter_host_runes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='coop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='census.cooptype'),
        ),
        migrations.RunPython(populate_coop_types)
    ]
