# Generated by Django 5.2.6 on 2025-09-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_cooptype_encounter_coop_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name', 'rune_level', 'weapon_level']},
        ),
        migrations.AlterModelOptions(
            name='cooptype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='cooptype',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
